addons:
  sonarcloud:
    organization: azak-azkaran-github
    token:
      secure: q50rXvnyL/BSICFZHaAc6cnHTJx8TV7y2xkczu+d1Q9Gl2FAZURtq8DvdtC60UnLZDlVDWdodGk7XncDlVQI/+YXObJoa2fO5t9wMckUCFhGThLOcMlktNvkj6hbzE2wlsQqMvwAKCXXqV2C1WpOy7mqHVEpkFMrkBpn9NwrWer9WzE+zHfCeom0aQRWTFv39fDUjmx3uyJsk+OA1piOlsAveDKJ+7HXTAHaxf2LRAPjawQL+deil8HluMvAI6QDGwb9Rh4gsTfxPaBomD0dR9gvsIW1wetYSavfoNkGEwRSMwGDt+v/MnNvqngG+9ugLnG3ClS4nlGmaIoModb8ySuBgbQgAyEe6codk9258ql3hB9VRkKD9Z6meF+PalJmmNSm2i23lM1x8mJpOhJOdrzeWfPvUXfVwsWDHt+9Is0VJ7XSZ6UDOTEFBVVhYMDTLlqHVW6EDWwxLVQsnRsbiUXr428AWIHOVAzYjehjFUUN/NE/iEA3Gjb4Rr+Fpk2DNckImcCFMipTgarDlrVUznhfOAGiaF2DOO66snrJjAHn00UW77TvcoQ1NyAgY+U2fr8i6st5OfwgZtikRuckjoVK3JNC0tVIlVrdDWN7tcLJlFmWctSI5S/TawHZkD8x/axq1+XrsXjaUG/AWwJkFD+/ZUVonV0TjIMU0k3VdO0=
env:
  global:
    secure: sRDoby7RP1G9y2g86V4x2HcFBtYE9eD6jQCwsPT2ZwfhhZy3z6fFKu6KX/Mq3ne2N8UDpwlYWFbdvUoliZMsZhix98w28b/z5HrYRYC3EDPTg/G3+vPEqrB21MnnMpXl0VjaZfiJPMLijErfEuR1NnYi1PSs2ggGvMlQ8AhGF+VTGCPS8ZMzMBDgXuMOi1KHUDKxE5FNOMtLq2MHG8W5CUV9xuhBvBQyy0UC5dBuFxzSMdgEHBkJQk5x0Y0IjVXBhz/Shx0ceT4JsyPdMaV5EhGvG7yUgBPDsJDe2FSV6sVG/qwbGG7c0SPyM57VD53f3YKzU2H1UA5fF/Si2D4L05T75GgDJEOn7TdPF39OcH7CUO+kebKc3xxFRNjwPjNuupoGRBfpwj3WPdyhVPxi8wnsTXOtuy8OzR4+lyWov0BWg5KyGbuQp0p5GsHan/+hHv7zDAO1k5RvuxdJohcTOEk+yPLVc9/8CTGEsHgJZn9rvBjUeyMBidYrMPwGXRaq3ZBegXAte2ccnDTNIMHEA1LmZ8gnT98X99ipOdeH5sXRaPZ4LLkA8F550VLNrxvyG4QixJ80A0R4n48DTvHVuqn2kVDpJ1wC+1juseWY//H9ZNbu1g7jHLyTWFGNR98NMGoFsthYpDecTDCuOC5ww5QTcR7nBEQ8vTxzNi2uGTs=
dist: bionic
language: go
sudo: false
go:
- tip
before_install:
- sudo apt-get update
- sudo apt-get -y install restic
- sudo curl -LO https://github.com/rfjakob/gocryptfs/releases/download/v1.7.1/gocryptfs_v1.7.1_linux-static_amd64.tar.gz
- sudo tar -C /usr/local/bin -xzf gocryptfs_v1.7.1_linux-static_amd64.tar.gz
- go get github.com/mattn/goveralls
script:
- make coverall
- echo "sonar.projectVersion=`git describe --tags --abbrev=0`" >> sonar-project.properties
- sonar-scanner
